version: '3'

services:
  dash_app:
    container_name: price_predictor
    image: scherbatskyjr/price-predictor:0.2
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./code:/app/code
      - ./model:/app/model
