name: Docker Build and Deploy

on:
  push:
    branches:
      - "0.3"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t scherbatskyjr/price-predictor:0.4 app
          docker push scherbatskyjr/price-predictor:0.4

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use SSH configurations
        uses: appleboy/ssh-action@master
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ml2023
          username: st124073
          port: 22

      - name: Deploy to Server
        run: |
          ssh ml2023 'cd dash && docker-compose up -d'
